site_name: Pybricks Cookbook
theme:
  name: readthedocs
  logo: img/logo.png
  favicon: img/logo.png
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.keys
  - pymdownx.superfences
  - attr_list
  - pymdownx.tabbed:
      alternate_style: true
extra_css:
  - css/tabs.css
  - css/extra.css
nav:
  - Введение: index.md
  - Установка:
      - Spike PRIME hub: primehub.md
  - Базовый код:
      - Создание кода: create_code.md
      - Инициализация: init.md
      - Функции: func.md
      - Структура: structure.md
      - Drive Base: db.md
      - Управление моторами: motors.md
  - Продвинутый код:
      - Советы: tips.md
  - Конструкции:
    - Studio 2.0: studio.md
  